# Generated by Django 4.2.5 on 2023-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('field', models.CharField(default='', max_length=200)),
                ('degree', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
