# Generated by Django 4.2.5 on 2023-09-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='field',
        ),
    ]
