# Generated by Django 4.2.5 on 2023-09-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0002_remove_user_degree_remove_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.CharField(default='', max_length=200),
        ),
    ]
