# Generated by Django 4.2.5 on 2023-09-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0005_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
