# Generated by Django 4.2.5 on 2023-09-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0008_remove_questions_comments_questions_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.CharField(default='', max_length=400),
        ),
    ]
