# Generated by Django 4.2.5 on 2023-09-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0009_questions_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='file1',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='file2',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
