# Generated by Django 4.2.5 on 2023-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0011_alter_questions_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file1',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='file2',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
